BEGIN;
insert into agriculture.crop_type values (1,'Hay and field crops');
insert into agriculture.crop_type values (2,'Total wheat');
insert into agriculture.crop_type values (3,'Spring wheat (excluding durum)');
insert into agriculture.crop_type values (4,'Durum wheat');
insert into agriculture.crop_type values (5,'Winter wheat');
insert into agriculture.crop_type values (6,'Oats');
insert into agriculture.crop_type values (7,'Barley');
insert into agriculture.crop_type values (8,'Mixed grains');
insert into agriculture.crop_type values (9,'Total corn');
insert into agriculture.crop_type values (10,'Corn for grain');
insert into agriculture.crop_type values (11,'Corn for silage');
insert into agriculture.crop_type values (12,'Total rye');
insert into agriculture.crop_type values (13,'Fall rye');
insert into agriculture.crop_type values (14,'Spring rye');
insert into agriculture.crop_type values (15,'Canola (rapeseed)');
insert into agriculture.crop_type values (16,'Soybeans');
insert into agriculture.crop_type values (17,'Flaxseed');
insert into agriculture.crop_type values (18,'Dry field peas');
insert into agriculture.crop_type values (19,'Chick peas');
insert into agriculture.crop_type values (20,'Lentils');
insert into agriculture.crop_type values (21,'Dry white beans');
insert into agriculture.crop_type values (22,'Other dry beans');
insert into agriculture.crop_type values (23,'Alfalfa and alfalfa mixtures');
insert into agriculture.crop_type values (24,'All other tame hay and fodder crops');
insert into agriculture.crop_type values (25,'Forage seed for seed');
insert into agriculture.crop_type values (26,'Potatoes');
insert into agriculture.crop_type values (27,'Mustard seed');
insert into agriculture.crop_type values (28,'Sunflowers');
insert into agriculture.crop_type values (29,'Canary seed');
insert into agriculture.crop_type values (30,'Ginseng');
insert into agriculture.crop_type values (31,'Buckwheat');
insert into agriculture.crop_type values (32,'Sugar beets');
insert into agriculture.crop_type values (33,'Caraway seed');
insert into agriculture.crop_type values (34,'Triticale');
insert into agriculture.crop_type values (35,'Other field crops');
COMMIT;